#! /usr/bin/env python

import time, datetime
import satnrt

if __name__ == "__main__":
   nr = satnrt.Nrt('ice')
   while True:
      nr.refresh(slippy=True)
      nr.refresh(fieldname="sst", slippy=True)
      print datetime.datetime.utcnow()
      time.sleep(3600*3)
